### ISSUE TITLE
Estuary Selective Events to Persist

### ISSUE THREAD

**Issue by JarredOlson** [Datastillery/smartcitiesdata#1129]
As Andy I would like to add stability and scalability to the system by only persisting events that I care about through Estuary.

AC:
- [x] Add an environment variable that is a list of event types 
- [ ] Events in that list should be persisted.
- [ ] Events that are not in that list should not be persisted
- [ ] Events to persist:

Tech Note:
Something along these lines would be a good starting point
`charts/deployment.yaml`
```yaml
...
          env:
          - name: EVENT_TYPES_TO_PERSIST
            value: {{ .Values.eventTypesToPersist }}
...
```

`charts/values.yaml`
```yaml
eventTypesToPersist:
  - dataset:update
  - error:dataset:update
  - organization:update
  - error:organization:update
  - dataset:disable
  - dataset:delete
  - data:write:complete
  - dataset:harvest:start
  - dataset:harvest:end
```
